name: COBOL CI

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build-and-run:
    runs-on: cobol

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile COBOL program
      run: |
        mkdir -p bin
        cobc -x -o bin/hello_world /Users/tgrall/projects/ghas-toulouse-demo/my-cobol-app/hello_world.cbl

    - name: Run COBOL program
      run: ./bin/hello_world

    - name: Output result to GitHub Summary
      run: |
        echo "🚀 Program Execution Result:" >> $GITHUB_STEP_SUMMARY
        ./bin/hello_world >> $GITHUB_STEP_SUMMARY
